fragment MeFields on UsersPermissionsMe {
  id
  username
  email
  confirmed
}

mutation register($user: UsersPermissionsRegisterInput!) {
  register(input: $user) {
    jwt
    user {
      ...MeFields
    }
  }
}

mutation login($identifier: String!, $password: String!) {
  login(input: {identifier: $identifier, password: $password}) {
    jwt
    user {
      ...MeFields
    }
  }
}

mutation forgotPassword($email: String!) {
  forgotPassword(email: $email) {
    ok
  }
}

mutation resetPassword(
  $password: String!
  $passwordConfirmation: String!
  $code: String!
) {
  resetPassword(
    password: $password
    passwordConfirmation: $passwordConfirmation
    code: $code
  ) {
    jwt
    user {
      ...MeFields
    }
  }
}
