fragment CarFields on Car {
  id
  name
  seats
  meeting
  departure
  phone_number
  details
  passengers {
    id
    name
  }
  event {
    id
    name
  }
}

mutation createCar($car: CarInput!) {
  createCar(input: {data: $car}) {
    car {
      ...CarFields
    }
  }
}

mutation updateCar($id: ID!, $carUpdate: editCarInput!) {
  updateCar(input: {where: {id: $id}, data: $carUpdate}) {
    car {
      ...CarFields
    }
  }
}

mutation deleteCar($id: ID!) {
  deleteCar(input: {where: {id: $id}}) {
    car {
      id
      name
    }
  }
}
