fragment EventFields on EventEntity {
  id
  attributes {
    uuid
    name
    description
    email
    date
    address
    latitude
    longitude
    position
    waitingPassengers {
      data {
        id
        attributes {
          name
          email
          location
          user {
            data {
              id
              attributes {
                firstName
                lastName
              }
            }
          }
        }
      }
    }
    travels(pagination: {limit: 100}) {
      data {
        id
        attributes {
          meeting
          departure
          details
          vehicleName
          phone_number
          seats
          passengers {
            data {
              id
              attributes {
                name
                location
                user {
                  data {
                    id
                    attributes {
                      firstName
                      lastName
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

mutation createEvent(
  $name: String!
  $email: String!
  $date: Date
  $address: String
  $latitude: Float
  $longitude: Float
  $description: String
  $newsletter: Boolean
) {
  createEvent(
    data: {
      name: $name
      email: $email
      date: $date
      latitude: $latitude
      longitude: $longitude
      address: $address
      description: $description
      newsletter: $newsletter
    }
  ) {
    data {
      ...EventFields
    }
  }
}

mutation updateEvent($uuid: String!, $eventUpdate: EventInput!) {
  updateEventByUUID(uuid: $uuid, data: $eventUpdate) {
    data {
      ...EventFields
    }
  }
}

query eventByUUID($uuid: String!) {
  eventByUUID(uuid: $uuid) {
    data {
      ...EventFields
    }
  }
}
