fragment EventFields on EventEntity {
  id
  attributes {
    uuid
    name
    description
    enabled_modules
    email
    lang
    administrators
    date
    address
    latitude
    longitude
    position
    waitingPassengers {
      data {
        id
        attributes {
          name
          email
          location
          user {
            data {
              id
              attributes {
                firstName
                lastName
              }
            }
          }
        }
      }
    }
    travels(pagination: {limit: 500}) {
      data {
        id
        attributes {
          meeting
          meeting_latitude
          meeting_longitude
          departureDate
          departureTime
          details
          vehicleName
          phone_number
          seats
          user {
            data {
              id
            }
          }
          passengers {
            data {
              id
              attributes {
                name
                location
                email
                phone
                user {
                  data {
                    id
                    attributes {
                      firstName
                      lastName
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

mutation createEvent($eventData: EventInput!) {
  createEvent(data: $eventData) {
    data {
      ...EventFields
    }
  }
}

mutation updateEvent($uuid: String!, $eventUpdate: EventInput!) {
  updateEventByUUID(uuid: $uuid, data: $eventUpdate) {
    data {
      ...EventFields
    }
  }
}

mutation addEventAdmin($eventId: ID!, $email: String!) {
  addEventAdmin(eventId: $eventId, email: $email) {
    data {
      id
      attributes {
        administrators
      }
    }
  }
}

mutation deleteEventAdmin($eventId: ID!, $email: String!) {
  deleteEventAdmin(eventId: $eventId, email: $email) {
    data {
      id
      attributes {
        administrators
      }
    }
  }
}

query eventByUUID($uuid: String!) {
  eventByUUID(uuid: $uuid) {
    data {
      ...EventFields
    }
  }
}
