query module($locale: I18NLocaleCode!) {
  module(locale: $locale) {
    data {
      attributes {
        caroster_plus_price
        caroster_plus_enabled
        caroster_plus_pricing_grid_id
        caroster_plus_publishable_key
      }
    }
  }
}
