query UserNotifications($maxItems: Int = 20) {
  notifications(pagination: {limit: $maxItems}, sort: "createdAt:DESC") {
    data {
      id
      attributes {
        type
        read
        createdAt
        user {
          data {
            id
            attributes {
              email
            }
          }
        }
        event {
          data {
            id
            attributes {
              name
              uuid
            }
          }
        }
      }
    }
  }
}

mutation readNotifications($id: ID) {
  readNotifications(id: $id) {
    data {
      id
      attributes {
        type
        read
      }
    }
  }
}
