query setting($locale: I18NLocaleCode!) {
  setting(locale: $locale) {
    data {
      id
      attributes {
        gtm_id
        about_link
        announcement
        matomo_script_url
        opencollective_link
        code_link
        stripe_dashboard_link
        tos_link
        data_policy_link
      }
    }
  }
}
