fragment VehicleFields on Vehicle {
  id
  name
  seats
  phone_number
}

query findUserVehicles {
  me {
    id
    username
    profile {
      vehicles {
        ...VehicleFields
      }
    }
  }
}

mutation createVehicle($vehicle: VehicleInput!) {
  createVehicle(input: {data: $vehicle}) {
    vehicle {
      ...VehicleFields
    }
  }
}

mutation updateVehicle($id: ID!, $vehicleUpdate: editVehicleInput!) {
  updateVehicle(input: {where: {id: $id}, data: $vehicleUpdate}) {
    vehicle {
      ...VehicleFields
    }
  }
}

mutation deleteVehicle($id: ID!) {
  deleteVehicle(input: {where: {id: $id}}) {
    vehicle {
      id
      name
    }
  }
}
