fragment VehicleFields on VehicleEntity {
  id
  attributes {
    name
    seats
    phone_number
  }
}

query findUserVehicles {
  me {
    id
    username
    profile {
      vehicles {
        data {
          ...VehicleFields
        }
      }
    }
  }
}

mutation deleteVehicle($id: ID!) {
  deleteVehicle(id: $id) {
    data {
      id
      attributes {
        name
      }
    }
  }
}
