name: Docker Build & Push
on: 
  push:
    branches:
      - main

env:
  USERNAME: octree
  IMAGE_NAME: caroster

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u $USERNAME -p $PASSWORD
        env:
          PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      - run: docker build -t $USERNAME/$IMAGE_NAME .
      - run: docker push $USERNAME/$IMAGE_NAME