name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      strapi:
        image: octree/caroster
        ports:
          - 1337:1337
        env:
          NODE_ENV: test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: yarn
      working-directory: frontend
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
      working-directory: frontend
    - name: Wait for Strapi to be ready
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: Run Playwright tests
      run: yarn playwright test
      working-directory: frontend
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
